FuelsCost: 0
FixedOMCost: 0
BudgetOfUncertainty_FixedOMCost: -1
MarketBuyPrices: 1
BudgetOfUncertainty_InvestmentCost: -1
InvestmentCost: 0
MarketSellPrices: 0
BudgetOfUncertainty_MarketSellPrices: -1
BudgetOfUncertainty: 1.0
BudgetOfUncertainty_MarketBuyPrices: 0.05
BudgetOfUncertainty_FuelPrices: -1
