UCommit: 2
OperationalReserves: 0
StorageLosses: 0
TimeDomainReduction: 0
VirtualChargeDischargeCost: 0 
StorageVirtualDischarge: 0
HourlyMatching: 0
HydrogenHourlyMatching: 0
ParameterScale: 0 # Flag to activate parameter scaling (i.e. converting MW to GW)
ObjScale: 1 #default value=1; utilize this parameter if model is of "ill form"
MultiStage: 1
ModelingToGenerateAlternatives: 0
ModelingtoGenerateAlternativeSlack: 0
MGAAnnualGeneration: 0
MethodofMorris: 0 
CO2Cap: 1
EnergyShareRequirement: 1
CapacityReserveMargin: 0
#MinCapReq: 0
#MaxCapReq: 0
MinBuildCapReq: 1
MaxBuildCapReq: 1
HydrogenMinimumProduction: 0
NetworkExpansion: 0
DCOPF: 0
Trans_Loss_Segments: 1
IncludeLossesInESR: 0
PrintModel: 1 #located in roote mGENX.jl folder
WriteShadowPrices: 0
WriteOutputs: "full"
OutputFullTimeSeries: 1
OverwriteResults: 1
PortfolioManagment: 0 #slice of day
Markets: 1
EnableJuMPStringNames: 1
ComputeConflicts: 1
PlanningReserveMargin: 1
RO: 1