ConvergenceTolerance: 0.01
DDP: 0
ModelYrsRemaining:
- 22
- 15
- 15
- 15
- 15
- 15
- 15
- 15
- 15
- 15
- 15
- 15
- 15
- 15
Myopic: 0
NumStages: 13
StageCumYears:
- 0
- 7
- 7
- 7
- 7
- 7
- 7
- 7
- 7
- 7
- 7
- 7
- 7
- 7
StageLengths:
- 7
- 15
- 15
- 15
- 15
- 15
- 15
- 15
- 15
- 15
- 15
- 15
- 15
- 15
WACC: 0.045
WriteIntermittentOutputs: 1
