IterativelyAddPeriods: 1
ExtremePeriods:
  Wind:
    System:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 1
        Max: 0
    Zone:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 0
        Max: 0
  Demand:
    System:
      Absolute:
        Min: 0
        Max: 1
      Integral:
        Min: 0
        Max: 0
    Zone:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 0
        Max: 0
  PV:
    System:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 1
        Max: 0
    Zone:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 0
        Max: 0
UseExtremePeriods: 1 # include outliers like extreme demand minimum solar or so
MinPeriods: 12 # we want 12 period a week from each month [But does it really take consecutive time points to represent month
MaxPeriods: 12
DemandWeight: 1
ClusterFuelPrices: 1
nReps: 100
Threshold: 0.05
TimestepsPerRepPeriod: 168 # The length of each representitive period in hours? 24 hours for 1 day, 168 for 1 week
IterateMethod: "cluster"
ScalingMethod: "S" # standardize(mean 0, variance 1) or normalized[0, 1]
ClusterMethod: "kmedoids" # or kmeans
WeightTotal: 8760
