CO2Cap: 1
CapResELCC: 1
CapacityReserveMargin: 0
ComputeConflicts: 1
EnergyShareRequirement: 0
Fixed_Dispatch: 0
Hourly_Pmin: 1
MGAAnnualGeneration: 0
MaxCapReq: 0
MinCapReq: 0
ModelingToGenerateAlternativeIterations: 2
ModelingToGenerateAlternatives: 0
ModelingtoGenerateAlternativeSlack: 0.05
MultiStage: 1
NetworkExpansion: 0
OperationalReserves: 0
ParameterScale: 0
PrintModel: 0
StorageLosses: 1
TimeDomainReduction: 0
Trans_Loss_Segments: 1
UCommit: 2
WriteShadowPrices: 1
ARO: 1
DirectMode: 0