HydrogenHourlyMatching: 0
NetworkExpansion: 0
OutputFolder: "results1.0"
WriteOutputs: "full"
HydrogenMinimumProduction: 0
OperationalReserves: 0
ParameterScale: 0
MaxBuildCapReq: 1
Markets: 1
EnableJuMPStringNames: 1
EnergyShareRequirement: 1
TimeDomainReduction: 0
PrintModel: 1
Trans_Loss_Segments: 1
CapacityReserveMargin: 0
ModelingtoGenerateAlternativeSlack: 0
MethodofMorris: 0
PlanningReserveMargin: 1
StorageVirtualDischarge: 0
MGAAnnualGeneration: 0
StorageLosses: 0
MultiStage: 0
MinBuildCapReq: 1
ObjScale: 1
IncludeLossesInESR: 0
OverwriteResults: 1
ComputeConflicts: 1
RO: 1
UCommit: 2
VirtualChargeDischargeCost: 0
ModelingToGenerateAlternatives: 0
DCOPF: 0
OutputFullTimeSeries: 1
HourlyMatching: 0
CO2Cap: 1
WriteShadowPrices: 0
PortfolioManagment: 0
